### ISSUE TITLE
Confusion in tutorial/part-zero, line 48

### ISSUE THREAD

**Issue by vitokhangnguyen** [gatsbyjs/gatsby-i18n-source#4]
I find this part confusing when I am translating it. Please tell me if I am wrong...

> If you’re new to the command line, “run command” means “type node --version in the command prompt, and hit the Enter key”. From here on, this is what we mean by “run command”

The part where "run `command`" means "type `node --version`..." sounds wrong to me.

**Comment by MichaelDeBoey** [comment]
Hi @vitokhangnguyen!

I think it's better to post this issue in the [original repo](https://github.com/gatsbyjs/gatsby).
